### ISSUE TITLE
dILP and Progol implementation

### ISSUE THREAD

**Issue by xihajun** [dj311/uob-summer-project#25]

**Comment by xihajun** [comment]
It seems that it will run forever

**Comment by xihajun** [comment]
dilp error
```
Performing Inference
Progress: |--------------------------------------------------| 0.0% Complete
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-52-b275270f0cf4> in <module>
      3 program_template
      4 dilp = DILP(langage_frame, B, P, N, program_template)
----> 5 dilp.train()

~/Documents/SummerProject/documents/DILP-Core/src/dilp/dilp.py in train(self, steps, name)
    126 
    127         for i in range(steps):
--> 128             grads = self.grad()
    129             optimizer.apply_gradients(zip(grads, self.__all_variables()),
    130                                       global_step=tf.train.get_or_create_global_step())

~/Documents/SummerProject/documents/DILP-Core/src/dilp/dilp.py in grad(self)
    159     def grad(self):
    160         with tfe.GradientTape() as tape:
--> 161             loss_value = self.loss(-1)
    162             weight_decay = 0.0
    163             regularization = 0

~/Documents/SummerProject/documents/DILP-Core/src/dilp/dilp.py in loss(self, batch_size)
    148         keys = np.array(
    149             [val for val in self.training_data.keys()], dtype=np.int32)
--> 150         outputs = tf.gather(self.deduction(), keys)
    151         if batch_size > 0:
    152             index = np.random.randint(0, len(labels), batch_size)

~/Documents/SummerProject/documents/DILP-Core/src/dilp/dilp.py in deduction(self)
    180             printProgressBar(step, self.program_template.T, prefix='Progress:',
    181                              suffix='Complete', length=50)
--> 182             valuation = self.inference_step(valuation)
    183         print('Inference Complete')
    184         return valuation

~/Documents/SummerProject/documents/DILP-Core/src/dilp/dilp.py in inference_step(self, valuation)
    190             for matrix in self.deduction_map[predicate]:
    191                 deduced_valuation += DILP.inference_single_predicate(
--> 192                     valuation, matrix, self.rule_weights[predicate])
    193         return deduced_valuation + valuation - deduced_valuation * valuation
    194 

~/Documents/SummerProject/documents/DILP-Core/src/dilp/dilp.py in inference_single_predicate(valuation, deduction_matrices, rule_weights)
    205             for matrix in deduction_matrices[i]:
    206                 result_valuations[i].append(
--> 207                     DILP.inference_single_clause(valuation, matrix))
    208 
    209         c_p = []  # flattened

~/Documents/SummerProject/documents/DILP-Core/src/dilp/dilp.py in inference_single_clause(valuation, X)
    226         X1 = X[:, :, 0, None]
    227         X2 = X[:, :, 1, None]
--> 228         Y1 = tf.gather_nd(params=valuation, indices=X1)
    229         Y2 = tf.gather_nd(params=valuation, indices=X2)
    230         Z = Y1 * Y2

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py in gather_nd(params, indices, name)
   3641       else:
   3642         message = e.message
-> 3643       _six.raise_from(_core._status_to_exception(e.code, message), None)
   3644   # Add nodes to the TensorFlow graph.
   3645   try:

~/anaconda3/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: indices has too many elements for int indexing: 4002340860 > 2147483647 [Op:GatherNd]```

**Comment by xihajun** [comment]
out of memory
```, <undefined>
Performing Inference
b'\rProgress: |--------------------------------------------------| 0.0% Complete'
WARNING:tensorflow:From /mnt/storage/home/mw18386/venv/lib/python3.5/site-packages/tensorflow/python/ops/resource_variable_ops.py:642: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
b'\rProgress: |\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88---------------------------------------------| 11.1% Complete'
b'\rProgress: |\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88---------------------------------------| 22.2% Complete'
Traceback (most recent call last):
  File "dilp.py", line 84, in <module>
    dilp.train()
  File "/mnt/storage/home/mw18386/summer/uob-summer-project/code/src/dilp/dilp.py", line 128, in train
    grads = self.grad()
  File "/mnt/storage/home/mw18386/summer/uob-summer-project/code/src/dilp/dilp.py", line 161, in grad
    loss_value = self.loss(-1)
  File "/mnt/storage/home/mw18386/summer/uob-summer-project/code/src/dilp/dilp.py", line 150, in loss
    outputs = tf.gather(self.deduction(), keys)
  File "/mnt/storage/home/mw18386/summer/uob-summer-project/code/src/dilp/dilp.py", line 182, in deduction
    valuation = self.inference_step(valuation)
  File "/mnt/storage/home/mw18386/summer/uob-summer-project/code/src/dilp/dilp.py", line 192, in inference_step
    valuation, matrix, self.rule_weights[predicate])
  File "/mnt/storage/home/mw18386/summer/uob-summer-project/code/src/dilp/dilp.py", line 207, in inference_single_predicate
    DILP.inference_single_clause(valuation, matrix))
  File "/mnt/storage/home/mw18386/summer/uob-summer-project/code/src/dilp/dilp.py", line 228, in inference_single_clause
    Y1 = tf.gather_nd(params=valuation, indices=X1)
  File "/mnt/storage/home/mw18386/venv/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3624, in gather_nd
    name, _ctx._post_execution_callbacks, params, indices)
MemoryError```
